spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Inventory-Management-Sys
    username: postgres
    password: 2004
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8081